README.md

Add React Day Berlin Conference

---

README.md

Add Angular Day Conference

---

README.md

feat:(general) Add conference Goto

---

README.md

add JSNation

---

README.md

Added DefCon under CyberSecurity

---

README.md

Alphabetize lists

---

README.md

Adding Magnolia JS to conference list.
- [Y ] Suggestion is not a duplicate
- [ Y] Suggestion is under the proper category
- [Y ] Link to conference is included 
- [Y ] Name of conference is included
- [Y ] Name and link are spelled correctly

added magnolia JS

---

README.md

added RenderATL to the tech conferences list

---

README.md

add ViteConf

---

README.md

Added React India

---

README.md

Added React Alicante

---

README.md

Added React Brussesls

---

README.md

Added ReactJS Day

---

README.md

Add some missing conferences

---

README.md

Added KCDC, Ran it through Grammarly

---

README.md

feat: add ng-rome conference

---

README.md

feat: Add codemotion conference

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
pull_request_template.md

I thought this list would be easier to read if it were formatted a little differently. The following changes were made:
- Conference names and links converted to `H3`
- More generalized label of `Location` used for compatibility with international and virtual conferences
- Removed HTML tags (I try not to use them in Markdown unless absolutely necessary)
I added a section to the `CONTRIBUTING.md` file as a template for how to format each entry. I also linted the markdown throughout the repo and made content corrections where needed.

Reformat repo

---

CONTRIBUTING.md
README.md

Add Jamstack conferences

---

README.md

Add Serverless Summit

---

README.md

Add JSHeroes conference
